"""add onboarded flag to user

Revision ID: 3d99d6ad09bc
Revises: 8a7e7487f288
Create Date: 2022-02-01 22:09:48.271404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d99d6ad09bc'
down_revision = '8a7e7487f288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarded', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarded')

    # ### end Alembic commands ###
