"""create initial tables

Revision ID: 4991b958931a
Revises: 
Create Date: 2022-01-24 13:56:35.429386

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4991b958931a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "score",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("edition", sa.Integer(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("raw", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score")
    op.drop_table("user")
    # ### end Alembic commands ###
