"""add slack_id to user

Revision ID: 8a7e7487f288
Revises: f3fbdd6014ce
Create Date: 2022-01-24 21:07:12.965104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7e7487f288'
down_revision = 'f3fbdd6014ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_slack_id'), ['slack_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_slack_id'), type_='unique')
        batch_op.drop_column('slack_id')

    # ### end Alembic commands ###
