WORDLE_WORD_LENGTH = 5
WORDLE_MAX_ATTEMPTS = 6
WORDLE_FAIL_INDICATOR = "X"

SELECT_TIMEZONE_ACTION_ID = "select_timezone"
TIMEZONE_CUSTOM_KEY = "timezone"
DAILY_TASKS_CUSTOM_KEY = "daily_tasks"

ISO_DATE_FORMAT = "%Y-%m-%d"
