import functools
from typing import List
from zoneinfo import ZoneInfo

from marisa_trie import Trie

PACIFIC_TIMEZONE_NAME = "America/Los_Angeles"
PACIFIC_TIME = ZoneInfo("America/Los_Angeles")


ALL_TIMEZONES = [
    "America/Martinique",
    "Pacific/Saipan",
    "Asia/Shanghai",
    "Asia/Oral",
    "Europe/Volgograd",
    "Antarctica/Mawson",
    "Antarctica/Davis",
    "Europe/Stockholm",
    "Africa/Algiers",
    "Pacific/Apia",
    "Pacific/Wake",
    "Etc/GMT-14",
    "America/Denver",
    "America/Cayman",
    "Europe/Zurich",
    "Asia/Yerevan",
    "Asia/Tbilisi",
    "CET",
    "Antarctica/Palmer",
    "Europe/Minsk",
    "Africa/Lagos",
    "Europe/Astrakhan",
    "America/Nome",
    "America/Maceio",
    "America/Argentina/Buenos_Aires",
    "America/Thunder_Bay",
    "Pacific/Norfolk",
    "Asia/Macau",
    "America/Indiana/Petersburg",
    "Pacific/Guam",
    "Asia/Samarkand",
    "Africa/Johannesburg",
    "Atlantic/Reykjavik",
    "America/Chicago",
    "Asia/Riyadh",
    "Asia/Krasnoyarsk",
    "Europe/Chisinau",
    "America/North_Dakota/Beulah",
    "Etc/GMT+8",
    "Europe/Podgorica",
    "Factory",
    "Atlantic/Cape_Verde",
    "Europe/Zaporozhye",
    "Africa/Tripoli",
    "Pacific/Auckland",
    "PST8PDT",
    "America/Indiana/Tell_City",
    "Europe/London",
    "Pacific/Chuuk",
    "America/Atikokan",
    "Africa/Lusaka",
    "America/Indiana/Marengo",
    "America/Argentina/Jujuy",
    "America/Tortola",
    "Asia/Aqtobe",
    "America/Hermosillo",
    "GMT",
    "America/Recife",
    "America/Resolute",
    "America/Caracas",
    "Asia/Tokyo",
    "Africa/Kinshasa",
    "Indian/Antananarivo",
    "Australia/Lindeman",
    "Europe/Bucharest",
    "America/Managua",
    "Pacific/Rarotonga",
    "America/Grenada",
    "Etc/GMT+11",
    "Etc/GMT+1",
    "Europe/Bratislava",
    "Asia/Kathmandu",
    "America/Panama",
    "America/Cambridge_Bay",
    "America/Sitka",
    "America/Kentucky/Louisville",
    "Asia/Urumqi",
    "America/Indiana/Winamac",
    "Europe/Copenhagen",
    "Africa/Cairo",
    "America/Noronha",
    "Asia/Singapore",
    "Antarctica/Syowa",
    "America/St_Kitts",
    "America/Guayaquil",
    "Australia/Lord_Howe",
    "Europe/Ljubljana",
    "Africa/Nouakchott",
    "Europe/Sofia",
    "Africa/Ouagadougou",
    "Europe/Simferopol",
    "Europe/Mariehamn",
    "Africa/El_Aaiun",
    "Indian/Comoro",
    "Australia/Darwin",
    "Europe/Samara",
    "America/Manaus",
    "Africa/Douala",
    "Asia/Qostanay",
    "Indian/Maldives",
    "Europe/Warsaw",
    "Australia/Adelaide",
    "Antarctica/Vostok",
    "Africa/Brazzaville",
    "Africa/Lubumbashi",
    "Pacific/Niue",
    "Asia/Kuching",
    "America/Chihuahua",
    "Etc/GMT-5",
    "Australia/Perth",
    "Europe/Istanbul",
    "Etc/GMT-11",
    "America/North_Dakota/New_Salem",
    "America/Merida",
    "America/Toronto",
    "Europe/Athens",
    "Asia/Amman",
    "Europe/Oslo",
    "Asia/Gaza",
    "America/Argentina/Rio_Gallegos",
    "Pacific/Fiji",
    "Europe/Kirov",
    "America/Miquelon",
    "Africa/Banjul",
    "Asia/Irkutsk",
    "Asia/Nicosia",
    "Asia/Jerusalem",
    "WET",
    "Atlantic/Azores",
    "America/Rainy_River",
    "America/Monterrey",
    "Africa/Bujumbura",
    "America/Yakutat",
    "Pacific/Pohnpei",
    "Asia/Vladivostok",
    "Asia/Jakarta",
    "America/Curacao",
    "America/Argentina/Mendoza",
    "America/Lima",
    "Africa/Tunis",
    "America/Nipigon",
    "America/St_Vincent",
    "America/Bahia",
    "Africa/Monrovia",
    "America/Menominee",
    "Pacific/Midway",
    "Etc/GMT-1",
    "Europe/Vilnius",
    "Europe/Vatican",
    "Pacific/Pitcairn",
    "Europe/Saratov",
    "Asia/Bahrain",
    "Asia/Dili",
    "America/La_Paz",
    "America/Indiana/Vevay",
    "America/Iqaluit",
    "America/Argentina/Cordoba",
    "Pacific/Funafuti",
    "Europe/Kiev",
    "America/Boise",
    "Pacific/Easter",
    "America/Metlakatla",
    "Asia/Yangon",
    "Pacific/Kosrae",
    "Asia/Yakutsk",
    "Antarctica/Rothera",
    "Asia/Bishkek",
    "America/Argentina/Salta",
    "Asia/Qatar",
    "Australia/Melbourne",
    "America/Indiana/Vincennes",
    "America/Adak",
    "Pacific/Kiritimati",
    "Asia/Sakhalin",
    "Etc/GMT-2",
    "Etc/UTC",
    "Europe/Skopje",
    "Indian/Mauritius",
    "Asia/Dushanbe",
    "Asia/Chita",
    "Asia/Kuwait",
    "Europe/Luxembourg",
    "Africa/Dakar",
    "Europe/Guernsey",
    "America/Lower_Princes",
    "Europe/Malta",
    "America/Barbados",
    "Asia/Aqtau",
    "America/Kralendijk",
    "Pacific/Marquesas",
    "America/Bahia_Banderas",
    "Atlantic/South_Georgia",
    "America/Anguilla",
    "America/Danmarkshavn",
    "Asia/Ashgabat",
    "MST7MDT",
    "Asia/Dubai",
    "Europe/Lisbon",
    "Europe/Jersey",
    "Asia/Srednekolymsk",
    "America/Thule",
    "America/St_Thomas",
    "Pacific/Kwajalein",
    "EST",
    "Etc/GMT+12",
    "Asia/Tashkent",
    "Africa/Mogadishu",
    "America/Winnipeg",
    "Pacific/Tongatapu",
    "Australia/Hobart",
    "Africa/Malabo",
    "America/New_York",
    "Europe/Amsterdam",
    "Asia/Pontianak",
    "America/Inuvik",
    "Indian/Christmas",
    "Europe/Tirane",
    "America/Paramaribo",
    "America/Santarem",
    "America/Montevideo",
    "Etc/GMT-4",
    "Etc/Greenwich",
    "Atlantic/Canary",
    "Pacific/Palau",
    "America/Grand_Turk",
    "Pacific/Fakaofo",
    "America/Asuncion",
    "Etc/Zulu",
    "Asia/Yekaterinburg",
    "Asia/Kabul",
    "America/Nuuk",
    "Australia/Eucla",
    "America/Phoenix",
    "America/Santiago",
    "America/Dominica",
    "Etc/GMT0",
    "Asia/Anadyr",
    "America/North_Dakota/Center",
    "Asia/Damascus",
    "Etc/GMT+10",
    "Europe/Vaduz",
    "America/Rankin_Inlet",
    "Etc/Universal",
    "Africa/Kigali",
    "Asia/Choibalsan",
    "Africa/Maseru",
    "Africa/Libreville",
    "Pacific/Guadalcanal",
    "America/Guatemala",
    "Europe/Zagreb",
    "America/Juneau",
    "Asia/Karachi",
    "Pacific/Kanton",
    "America/Creston",
    "America/Santo_Domingo",
    "America/Whitehorse",
    "Etc/GMT+3",
    "America/Sao_Paulo",
    "Africa/Nairobi",
    "America/Detroit",
    "Antarctica/McMurdo",
    "Etc/GMT+7",
    "Etc/GMT-3",
    "Asia/Baku",
    "America/Argentina/Catamarca",
    "Etc/GMT-0",
    "America/Yellowknife",
    "Africa/Windhoek",
    "America/Fortaleza",
    "America/Blanc-Sablon",
    "America/Dawson_Creek",
    "America/El_Salvador",
    "Europe/Andorra",
    "Indian/Chagos",
    "Africa/Harare",
    "Asia/Ust-Nera",
    "Asia/Dhaka",
    "Asia/Seoul",
    "America/Mexico_City",
    "America/Cayenne",
    "Europe/Berlin",
    "Europe/Dublin",
    "Africa/Mbabane",
    "Indian/Cocos",
    "Asia/Hovd",
    "Pacific/Majuro",
    "Europe/Budapest",
    "America/Marigot",
    "Europe/Madrid",
    "Asia/Kamchatka",
    "America/Argentina/Ushuaia",
    "Etc/GMT+4",
    "Etc/GMT-6",
    "Africa/Kampala",
    "Europe/San_Marino",
    "America/Indiana/Indianapolis",
    "MET",
    "Pacific/Tarawa",
    "America/Nassau",
    "America/Eirunepe",
    "Etc/GMT-10",
    "America/Goose_Bay",
    "Asia/Jayapura",
    "Etc/GMT-9",
    "America/Swift_Current",
    "America/Edmonton",
    "America/Argentina/San_Luis",
    "Europe/Belgrade",
    "Asia/Barnaul",
    "HST",
    "America/Campo_Grande",
    "Asia/Almaty",
    "Pacific/Port_Moresby",
    "America/Punta_Arenas",
    "Asia/Novokuznetsk",
    "Asia/Vientiane",
    "Etc/GMT+5",
    "Indian/Mahe",
    "Europe/Brussels",
    "Atlantic/Bermuda",
    "America/Cuiaba",
    "Africa/Bamako",
    "America/Cancun",
    "America/Havana",
    "America/Costa_Rica",
    "America/St_Johns",
    "Europe/Uzhgorod",
    "Africa/Ndjamena",
    "Africa/Khartoum",
    "Asia/Omsk",
    "Europe/Isle_of_Man",
    "Atlantic/St_Helena",
    "Antarctica/DumontDUrville",
    "Atlantic/Faroe",
    "Africa/Juba",
    "EET",
    "Asia/Baghdad",
    "Antarctica/Troll",
    "Africa/Freetown",
    "Africa/Djibouti",
    "America/Puerto_Rico",
    "Africa/Niamey",
    "Europe/Gibraltar",
    "Europe/Tallinn",
    "America/Araguaina",
    "Etc/GMT-8",
    "Asia/Magadan",
    "CST6CDT",
    "America/Anchorage",
    "Etc/GMT-13",
    "Europe/Rome",
    "EST5EDT",
    "America/Scoresbysund",
    "America/Vancouver",
    "Etc/GMT+2",
    "Pacific/Bougainville",
    "Pacific/Tahiti",
    "Africa/Bangui",
    "Africa/Accra",
    "America/Mazatlan",
    "America/St_Lucia",
    "Pacific/Noumea",
    "America/Antigua",
    "Asia/Novosibirsk",
    "America/Belem",
    "Africa/Casablanca",
    "Africa/Conakry",
    "Asia/Tomsk",
    "Africa/Dar_es_Salaam",
    "Australia/Broken_Hill",
    "America/Indiana/Knox",
    "America/Halifax",
    "Asia/Muscat",
    "Africa/Luanda",
    "MST",
    "Asia/Famagusta",
    "Pacific/Nauru",
    "America/Port-au-Prince",
    "America/Los_Angeles",
    "Asia/Kuala_Lumpur",
    "America/Ojinaga",
    "Africa/Blantyre",
    "Asia/Taipei",
    "America/Fort_Nelson",
    "America/Jamaica",
    "Asia/Qyzylorda",
    "Pacific/Wallis",
    "Europe/Helsinki",
    "Africa/Maputo",
    "America/Boa_Vista",
    "America/Dawson",
    "America/Regina",
    "Europe/Moscow",
    "Africa/Abidjan",
    "Africa/Bissau",
    "Europe/Ulyanovsk",
    "Asia/Hebron",
    "Atlantic/Madeira",
    "Pacific/Galapagos",
    "Asia/Ho_Chi_Minh",
    "America/Kentucky/Monticello",
    "Asia/Phnom_Penh",
    "Europe/Vienna",
    "Asia/Atyrau",
    "America/Glace_Bay",
    "Antarctica/Casey",
    "Etc/GMT+0",
    "Australia/Sydney",
    "Africa/Gaborone",
    "Asia/Beirut",
    "Pacific/Efate",
    "Asia/Thimphu",
    "Antarctica/Macquarie",
    "Africa/Sao_Tome",
    "Etc/GMT-12",
    "America/Bogota",
    "Indian/Kerguelen",
    "Africa/Lome",
    "America/St_Barthelemy",
    "America/Montserrat",
    "America/Aruba",
    "Asia/Colombo",
    "America/Guadeloupe",
    "Asia/Hong_Kong",
    "Indian/Mayotte",
    "Africa/Porto-Novo",
    "Pacific/Pago_Pago",
    "Asia/Pyongyang",
    "Europe/Busingen",
    "Asia/Khandyga",
    "Europe/Prague",
    "Europe/Monaco",
    "Europe/Paris",
    "America/Porto_Velho",
    "Arctic/Longyearbyen",
    "Etc/GMT+9",
    "Pacific/Chatham",
    "Asia/Istanbul",
    "Europe/Kaliningrad",
    "America/Argentina/La_Rioja",
    "Europe/Nicosia",
    "Asia/Kolkata",
    "Europe/Sarajevo",
    "Australia/Brisbane",
    "America/Argentina/Tucuman",
    "Asia/Brunei",
    "Indian/Reunion",
    "Africa/Ceuta",
    "America/Tijuana",
    "Asia/Tehran",
    "America/Belize",
    "America/Guyana",
    "Etc/GMT-7",
    "Asia/Aden",
    "America/Moncton",
    "America/Pangnirtung",
    "Africa/Addis_Ababa",
    "Etc/GMT+6",
    "Africa/Asmara",
    "Atlantic/Stanley",
    "America/Matamoros",
    "America/Argentina/San_Juan",
    "Asia/Manila",
    "America/Tegucigalpa",
    "America/Port_of_Spain",
    "Pacific/Gambier",
    "Europe/Riga",
    "Pacific/Honolulu",
    "Asia/Makassar",
    "Asia/Bangkok",
    "Asia/Ulaanbaatar",
    "America/Rio_Branco",
    "Etc/GMT",
]

ALL_TIMEZONES_WITH_OFFSET = [
    "(UTC - 4.0) America/Martinique",
    "(UTC + 10.0) Pacific/Saipan",
    "(UTC + 8.0) Asia/Shanghai",
    "(UTC + 5.0) Asia/Oral",
    "(UTC + 3.0) Europe/Volgograd",
    "(UTC + 5.0) Antarctica/Mawson",
    "(UTC + 7.0) Antarctica/Davis",
    "(UTC + 1.0) Europe/Stockholm",
    "(UTC + 1.0) Africa/Algiers",
    "(UTC + 13.0) Pacific/Apia",
    "(UTC + 12.0) Pacific/Wake",
    "(UTC + 14.0) Etc/GMT-14",
    "(UTC - 7.0) America/Denver",
    "(UTC - 5.0) America/Cayman",
    "(UTC + 1.0) Europe/Zurich",
    "(UTC + 4.0) Asia/Yerevan",
    "(UTC + 4.0) Asia/Tbilisi",
    "(UTC + 1.0) CET",
    "(UTC - 3.0) Antarctica/Palmer",
    "(UTC + 3.0) Europe/Minsk",
    "(UTC + 1.0) Africa/Lagos",
    "(UTC + 4.0) Europe/Astrakhan",
    "(UTC - 9.0) America/Nome",
    "(UTC - 3.0) America/Maceio",
    "(UTC - 3.0) America/Argentina/Buenos_Aires",
    "(UTC - 5.0) America/Thunder_Bay",
    "(UTC + 12.0) Pacific/Norfolk",
    "(UTC + 8.0) Asia/Macau",
    "(UTC - 5.0) America/Indiana/Petersburg",
    "(UTC + 10.0) Pacific/Guam",
    "(UTC + 5.0) Asia/Samarkand",
    "(UTC + 2.0) Africa/Johannesburg",
    "(UTC - 0.0) Atlantic/Reykjavik",
    "(UTC - 6.0) America/Chicago",
    "(UTC + 3.0) Asia/Riyadh",
    "(UTC + 7.0) Asia/Krasnoyarsk",
    "(UTC + 2.0) Europe/Chisinau",
    "(UTC - 6.0) America/North_Dakota/Beulah",
    "(UTC - 8.0) Etc/GMT+8",
    "(UTC + 1.0) Europe/Podgorica",
    "(UTC - 0.0) Factory",
    "(UTC - 1.0) Atlantic/Cape_Verde",
    "(UTC + 2.0) Europe/Zaporozhye",
    "(UTC + 2.0) Africa/Tripoli",
    "(UTC + 13.0) Pacific/Auckland",
    "(UTC - 8.0) PST8PDT",
    "(UTC - 6.0) America/Indiana/Tell_City",
    "(UTC - 0.0) Europe/London",
    "(UTC + 10.0) Pacific/Chuuk",
    "(UTC - 5.0) America/Atikokan",
    "(UTC + 2.0) Africa/Lusaka",
    "(UTC - 5.0) America/Indiana/Marengo",
    "(UTC - 3.0) America/Argentina/Jujuy",
    "(UTC - 4.0) America/Tortola",
    "(UTC + 5.0) Asia/Aqtobe",
    "(UTC - 7.0) America/Hermosillo",
    "(UTC - 0.0) GMT",
    "(UTC - 3.0) America/Recife",
    "(UTC - 6.0) America/Resolute",
    "(UTC - 4.0) America/Caracas",
    "(UTC + 9.0) Asia/Tokyo",
    "(UTC + 1.0) Africa/Kinshasa",
    "(UTC + 3.0) Indian/Antananarivo",
    "(UTC + 10.0) Australia/Lindeman",
    "(UTC + 2.0) Europe/Bucharest",
    "(UTC - 6.0) America/Managua",
    "(UTC - 10.0) Pacific/Rarotonga",
    "(UTC - 4.0) America/Grenada",
    "(UTC - 11.0) Etc/GMT+11",
    "(UTC - 1.0) Etc/GMT+1",
    "(UTC + 1.0) Europe/Bratislava",
    "(UTC + 5.75) Asia/Kathmandu",
    "(UTC - 5.0) America/Panama",
    "(UTC - 7.0) America/Cambridge_Bay",
    "(UTC - 9.0) America/Sitka",
    "(UTC - 5.0) America/Kentucky/Louisville",
    "(UTC + 6.0) Asia/Urumqi",
    "(UTC - 5.0) America/Indiana/Winamac",
    "(UTC + 1.0) Europe/Copenhagen",
    "(UTC + 2.0) Africa/Cairo",
    "(UTC - 2.0) America/Noronha",
    "(UTC + 8.0) Asia/Singapore",
    "(UTC + 3.0) Antarctica/Syowa",
    "(UTC - 4.0) America/St_Kitts",
    "(UTC - 5.0) America/Guayaquil",
    "(UTC + 11.0) Australia/Lord_Howe",
    "(UTC + 1.0) Europe/Ljubljana",
    "(UTC - 0.0) Africa/Nouakchott",
    "(UTC + 2.0) Europe/Sofia",
    "(UTC - 0.0) Africa/Ouagadougou",
    "(UTC + 3.0) Europe/Simferopol",
    "(UTC + 2.0) Europe/Mariehamn",
    "(UTC + 1.0) Africa/El_Aaiun",
    "(UTC + 3.0) Indian/Comoro",
    "(UTC + 9.5) Australia/Darwin",
    "(UTC + 4.0) Europe/Samara",
    "(UTC - 4.0) America/Manaus",
    "(UTC + 1.0) Africa/Douala",
    "(UTC + 6.0) Asia/Qostanay",
    "(UTC + 5.0) Indian/Maldives",
    "(UTC + 1.0) Europe/Warsaw",
    "(UTC + 10.5) Australia/Adelaide",
    "(UTC + 6.0) Antarctica/Vostok",
    "(UTC + 1.0) Africa/Brazzaville",
    "(UTC + 2.0) Africa/Lubumbashi",
    "(UTC - 11.0) Pacific/Niue",
    "(UTC + 8.0) Asia/Kuching",
    "(UTC - 7.0) America/Chihuahua",
    "(UTC + 5.0) Etc/GMT-5",
    "(UTC + 8.0) Australia/Perth",
    "(UTC + 3.0) Europe/Istanbul",
    "(UTC + 11.0) Etc/GMT-11",
    "(UTC - 6.0) America/North_Dakota/New_Salem",
    "(UTC - 6.0) America/Merida",
    "(UTC - 5.0) America/Toronto",
    "(UTC + 2.0) Europe/Athens",
    "(UTC + 2.0) Asia/Amman",
    "(UTC + 1.0) Europe/Oslo",
    "(UTC + 2.0) Asia/Gaza",
    "(UTC - 3.0) America/Argentina/Rio_Gallegos",
    "(UTC + 12.0) Pacific/Fiji",
    "(UTC + 3.0) Europe/Kirov",
    "(UTC - 3.0) America/Miquelon",
    "(UTC - 0.0) Africa/Banjul",
    "(UTC + 8.0) Asia/Irkutsk",
    "(UTC + 2.0) Asia/Nicosia",
    "(UTC + 2.0) Asia/Jerusalem",
    "(UTC - 0.0) WET",
    "(UTC - 1.0) Atlantic/Azores",
    "(UTC - 6.0) America/Rainy_River",
    "(UTC - 6.0) America/Monterrey",
    "(UTC + 2.0) Africa/Bujumbura",
    "(UTC - 9.0) America/Yakutat",
    "(UTC + 11.0) Pacific/Pohnpei",
    "(UTC + 10.0) Asia/Vladivostok",
    "(UTC + 7.0) Asia/Jakarta",
    "(UTC - 4.0) America/Curacao",
    "(UTC - 3.0) America/Argentina/Mendoza",
    "(UTC - 5.0) America/Lima",
    "(UTC + 1.0) Africa/Tunis",
    "(UTC - 5.0) America/Nipigon",
    "(UTC - 4.0) America/St_Vincent",
    "(UTC - 3.0) America/Bahia",
    "(UTC - 0.0) Africa/Monrovia",
    "(UTC - 6.0) America/Menominee",
    "(UTC - 11.0) Pacific/Midway",
    "(UTC + 1.0) Etc/GMT-1",
    "(UTC + 2.0) Europe/Vilnius",
    "(UTC + 1.0) Europe/Vatican",
    "(UTC - 8.0) Pacific/Pitcairn",
    "(UTC + 4.0) Europe/Saratov",
    "(UTC + 3.0) Asia/Bahrain",
    "(UTC + 9.0) Asia/Dili",
    "(UTC - 4.0) America/La_Paz",
    "(UTC - 5.0) America/Indiana/Vevay",
    "(UTC - 5.0) America/Iqaluit",
    "(UTC - 3.0) America/Argentina/Cordoba",
    "(UTC + 12.0) Pacific/Funafuti",
    "(UTC + 2.0) Europe/Kiev",
    "(UTC - 7.0) America/Boise",
    "(UTC - 5.0) Pacific/Easter",
    "(UTC - 9.0) America/Metlakatla",
    "(UTC + 6.5) Asia/Yangon",
    "(UTC + 11.0) Pacific/Kosrae",
    "(UTC + 9.0) Asia/Yakutsk",
    "(UTC - 3.0) Antarctica/Rothera",
    "(UTC + 6.0) Asia/Bishkek",
    "(UTC - 3.0) America/Argentina/Salta",
    "(UTC + 3.0) Asia/Qatar",
    "(UTC + 11.0) Australia/Melbourne",
    "(UTC - 5.0) America/Indiana/Vincennes",
    "(UTC - 10.0) America/Adak",
    "(UTC + 14.0) Pacific/Kiritimati",
    "(UTC + 11.0) Asia/Sakhalin",
    "(UTC + 2.0) Etc/GMT-2",
    "(UTC - 0.0) Etc/UTC",
    "(UTC + 1.0) Europe/Skopje",
    "(UTC + 4.0) Indian/Mauritius",
    "(UTC + 5.0) Asia/Dushanbe",
    "(UTC + 9.0) Asia/Chita",
    "(UTC + 3.0) Asia/Kuwait",
    "(UTC + 1.0) Europe/Luxembourg",
    "(UTC - 0.0) Africa/Dakar",
    "(UTC - 0.0) Europe/Guernsey",
    "(UTC - 4.0) America/Lower_Princes",
    "(UTC + 1.0) Europe/Malta",
    "(UTC - 4.0) America/Barbados",
    "(UTC + 5.0) Asia/Aqtau",
    "(UTC - 4.0) America/Kralendijk",
    "(UTC - 9.5) Pacific/Marquesas",
    "(UTC - 6.0) America/Bahia_Banderas",
    "(UTC - 2.0) Atlantic/South_Georgia",
    "(UTC - 4.0) America/Anguilla",
    "(UTC - 0.0) America/Danmarkshavn",
    "(UTC + 5.0) Asia/Ashgabat",
    "(UTC - 7.0) MST7MDT",
    "(UTC + 4.0) Asia/Dubai",
    "(UTC - 0.0) Europe/Lisbon",
    "(UTC - 0.0) Europe/Jersey",
    "(UTC + 11.0) Asia/Srednekolymsk",
    "(UTC - 4.0) America/Thule",
    "(UTC - 4.0) America/St_Thomas",
    "(UTC + 12.0) Pacific/Kwajalein",
    "(UTC - 5.0) EST",
    "(UTC - 12.0) Etc/GMT+12",
    "(UTC + 5.0) Asia/Tashkent",
    "(UTC + 3.0) Africa/Mogadishu",
    "(UTC - 6.0) America/Winnipeg",
    "(UTC + 13.0) Pacific/Tongatapu",
    "(UTC + 11.0) Australia/Hobart",
    "(UTC + 1.0) Africa/Malabo",
    "(UTC - 5.0) America/New_York",
    "(UTC + 1.0) Europe/Amsterdam",
    "(UTC + 7.0) Asia/Pontianak",
    "(UTC - 7.0) America/Inuvik",
    "(UTC + 7.0) Indian/Christmas",
    "(UTC + 1.0) Europe/Tirane",
    "(UTC - 3.0) America/Paramaribo",
    "(UTC - 3.0) America/Santarem",
    "(UTC - 3.0) America/Montevideo",
    "(UTC + 4.0) Etc/GMT-4",
    "(UTC - 0.0) Etc/Greenwich",
    "(UTC - 0.0) Atlantic/Canary",
    "(UTC + 9.0) Pacific/Palau",
    "(UTC - 5.0) America/Grand_Turk",
    "(UTC + 13.0) Pacific/Fakaofo",
    "(UTC - 3.0) America/Asuncion",
    "(UTC - 0.0) Etc/Zulu",
    "(UTC + 5.0) Asia/Yekaterinburg",
    "(UTC + 4.5) Asia/Kabul",
    "(UTC - 3.0) America/Nuuk",
    "(UTC + 8.75) Australia/Eucla",
    "(UTC - 7.0) America/Phoenix",
    "(UTC - 3.0) America/Santiago",
    "(UTC - 4.0) America/Dominica",
    "(UTC - 0.0) Etc/GMT0",
    "(UTC + 12.0) Asia/Anadyr",
    "(UTC - 6.0) America/North_Dakota/Center",
    "(UTC + 2.0) Asia/Damascus",
    "(UTC - 10.0) Etc/GMT+10",
    "(UTC + 1.0) Europe/Vaduz",
    "(UTC - 6.0) America/Rankin_Inlet",
    "(UTC - 0.0) Etc/Universal",
    "(UTC + 2.0) Africa/Kigali",
    "(UTC + 8.0) Asia/Choibalsan",
    "(UTC + 2.0) Africa/Maseru",
    "(UTC + 1.0) Africa/Libreville",
    "(UTC + 11.0) Pacific/Guadalcanal",
    "(UTC - 6.0) America/Guatemala",
    "(UTC + 1.0) Europe/Zagreb",
    "(UTC - 9.0) America/Juneau",
    "(UTC + 5.0) Asia/Karachi",
    "(UTC + 13.0) Pacific/Kanton",
    "(UTC - 7.0) America/Creston",
    "(UTC - 4.0) America/Santo_Domingo",
    "(UTC - 7.0) America/Whitehorse",
    "(UTC - 3.0) Etc/GMT+3",
    "(UTC - 3.0) America/Sao_Paulo",
    "(UTC + 3.0) Africa/Nairobi",
    "(UTC - 5.0) America/Detroit",
    "(UTC + 13.0) Antarctica/McMurdo",
    "(UTC - 7.0) Etc/GMT+7",
    "(UTC + 3.0) Etc/GMT-3",
    "(UTC + 4.0) Asia/Baku",
    "(UTC - 3.0) America/Argentina/Catamarca",
    "(UTC - 0.0) Etc/GMT-0",
    "(UTC - 7.0) America/Yellowknife",
    "(UTC + 2.0) Africa/Windhoek",
    "(UTC - 3.0) America/Fortaleza",
    "(UTC - 4.0) America/Blanc-Sablon",
    "(UTC - 7.0) America/Dawson_Creek",
    "(UTC - 6.0) America/El_Salvador",
    "(UTC + 1.0) Europe/Andorra",
    "(UTC + 6.0) Indian/Chagos",
    "(UTC + 2.0) Africa/Harare",
    "(UTC + 10.0) Asia/Ust-Nera",
    "(UTC + 6.0) Asia/Dhaka",
    "(UTC + 9.0) Asia/Seoul",
    "(UTC - 6.0) America/Mexico_City",
    "(UTC - 3.0) America/Cayenne",
    "(UTC + 1.0) Europe/Berlin",
    "(UTC - 0.0) Europe/Dublin",
    "(UTC + 2.0) Africa/Mbabane",
    "(UTC + 6.5) Indian/Cocos",
    "(UTC + 7.0) Asia/Hovd",
    "(UTC + 12.0) Pacific/Majuro",
    "(UTC + 1.0) Europe/Budapest",
    "(UTC - 4.0) America/Marigot",
    "(UTC + 1.0) Europe/Madrid",
    "(UTC + 12.0) Asia/Kamchatka",
    "(UTC - 3.0) America/Argentina/Ushuaia",
    "(UTC - 4.0) Etc/GMT+4",
    "(UTC + 6.0) Etc/GMT-6",
    "(UTC + 3.0) Africa/Kampala",
    "(UTC + 1.0) Europe/San_Marino",
    "(UTC - 5.0) America/Indiana/Indianapolis",
    "(UTC + 1.0) MET",
    "(UTC + 12.0) Pacific/Tarawa",
    "(UTC - 5.0) America/Nassau",
    "(UTC - 5.0) America/Eirunepe",
    "(UTC + 10.0) Etc/GMT-10",
    "(UTC - 4.0) America/Goose_Bay",
    "(UTC + 9.0) Asia/Jayapura",
    "(UTC + 9.0) Etc/GMT-9",
    "(UTC - 6.0) America/Swift_Current",
    "(UTC - 7.0) America/Edmonton",
    "(UTC - 3.0) America/Argentina/San_Luis",
    "(UTC + 1.0) Europe/Belgrade",
    "(UTC + 7.0) Asia/Barnaul",
    "(UTC - 10.0) HST",
    "(UTC - 4.0) America/Campo_Grande",
    "(UTC + 6.0) Asia/Almaty",
    "(UTC + 10.0) Pacific/Port_Moresby",
    "(UTC - 3.0) America/Punta_Arenas",
    "(UTC + 7.0) Asia/Novokuznetsk",
    "(UTC + 7.0) Asia/Vientiane",
    "(UTC - 5.0) Etc/GMT+5",
    "(UTC + 4.0) Indian/Mahe",
    "(UTC + 1.0) Europe/Brussels",
    "(UTC - 4.0) Atlantic/Bermuda",
    "(UTC - 4.0) America/Cuiaba",
    "(UTC - 0.0) Africa/Bamako",
    "(UTC - 5.0) America/Cancun",
    "(UTC - 5.0) America/Havana",
    "(UTC - 6.0) America/Costa_Rica",
    "(UTC - 3.5) America/St_Johns",
    "(UTC + 2.0) Europe/Uzhgorod",
    "(UTC + 1.0) Africa/Ndjamena",
    "(UTC + 2.0) Africa/Khartoum",
    "(UTC + 6.0) Asia/Omsk",
    "(UTC - 0.0) Europe/Isle_of_Man",
    "(UTC - 0.0) Atlantic/St_Helena",
    "(UTC + 10.0) Antarctica/DumontDUrville",
    "(UTC - 0.0) Atlantic/Faroe",
    "(UTC + 2.0) Africa/Juba",
    "(UTC + 2.0) EET",
    "(UTC + 3.0) Asia/Baghdad",
    "(UTC - 0.0) Antarctica/Troll",
    "(UTC - 0.0) Africa/Freetown",
    "(UTC + 3.0) Africa/Djibouti",
    "(UTC - 4.0) America/Puerto_Rico",
    "(UTC + 1.0) Africa/Niamey",
    "(UTC + 1.0) Europe/Gibraltar",
    "(UTC + 2.0) Europe/Tallinn",
    "(UTC - 3.0) America/Araguaina",
    "(UTC + 8.0) Etc/GMT-8",
    "(UTC + 11.0) Asia/Magadan",
    "(UTC - 6.0) CST6CDT",
    "(UTC - 9.0) America/Anchorage",
    "(UTC + 13.0) Etc/GMT-13",
    "(UTC + 1.0) Europe/Rome",
    "(UTC - 5.0) EST5EDT",
    "(UTC - 1.0) America/Scoresbysund",
    "(UTC - 8.0) America/Vancouver",
    "(UTC - 2.0) Etc/GMT+2",
    "(UTC + 11.0) Pacific/Bougainville",
    "(UTC - 10.0) Pacific/Tahiti",
    "(UTC + 1.0) Africa/Bangui",
    "(UTC - 0.0) Africa/Accra",
    "(UTC - 7.0) America/Mazatlan",
    "(UTC - 4.0) America/St_Lucia",
    "(UTC + 11.0) Pacific/Noumea",
    "(UTC - 4.0) America/Antigua",
    "(UTC + 7.0) Asia/Novosibirsk",
    "(UTC - 3.0) America/Belem",
    "(UTC + 1.0) Africa/Casablanca",
    "(UTC - 0.0) Africa/Conakry",
    "(UTC + 7.0) Asia/Tomsk",
    "(UTC + 3.0) Africa/Dar_es_Salaam",
    "(UTC + 10.5) Australia/Broken_Hill",
    "(UTC - 6.0) America/Indiana/Knox",
    "(UTC - 4.0) America/Halifax",
    "(UTC + 4.0) Asia/Muscat",
    "(UTC + 1.0) Africa/Luanda",
    "(UTC - 7.0) MST",
    "(UTC + 2.0) Asia/Famagusta",
    "(UTC + 12.0) Pacific/Nauru",
    "(UTC - 5.0) America/Port-au-Prince",
    "(UTC - 8.0) America/Los_Angeles",
    "(UTC + 8.0) Asia/Kuala_Lumpur",
    "(UTC - 7.0) America/Ojinaga",
    "(UTC + 2.0) Africa/Blantyre",
    "(UTC + 8.0) Asia/Taipei",
    "(UTC - 7.0) America/Fort_Nelson",
    "(UTC - 5.0) America/Jamaica",
    "(UTC + 5.0) Asia/Qyzylorda",
    "(UTC + 12.0) Pacific/Wallis",
    "(UTC + 2.0) Europe/Helsinki",
    "(UTC + 2.0) Africa/Maputo",
    "(UTC - 4.0) America/Boa_Vista",
    "(UTC - 7.0) America/Dawson",
    "(UTC - 6.0) America/Regina",
    "(UTC + 3.0) Europe/Moscow",
    "(UTC - 0.0) Africa/Abidjan",
    "(UTC - 0.0) Africa/Bissau",
    "(UTC + 4.0) Europe/Ulyanovsk",
    "(UTC + 2.0) Asia/Hebron",
    "(UTC - 0.0) Atlantic/Madeira",
    "(UTC - 6.0) Pacific/Galapagos",
    "(UTC + 7.0) Asia/Ho_Chi_Minh",
    "(UTC - 5.0) America/Kentucky/Monticello",
    "(UTC + 7.0) Asia/Phnom_Penh",
    "(UTC + 1.0) Europe/Vienna",
    "(UTC + 5.0) Asia/Atyrau",
    "(UTC - 4.0) America/Glace_Bay",
    "(UTC + 11.0) Antarctica/Casey",
    "(UTC - 0.0) Etc/GMT+0",
    "(UTC + 11.0) Australia/Sydney",
    "(UTC + 2.0) Africa/Gaborone",
    "(UTC + 2.0) Asia/Beirut",
    "(UTC + 11.0) Pacific/Efate",
    "(UTC + 6.0) Asia/Thimphu",
    "(UTC + 11.0) Antarctica/Macquarie",
    "(UTC - 0.0) Africa/Sao_Tome",
    "(UTC + 12.0) Etc/GMT-12",
    "(UTC - 5.0) America/Bogota",
    "(UTC + 5.0) Indian/Kerguelen",
    "(UTC - 0.0) Africa/Lome",
    "(UTC - 4.0) America/St_Barthelemy",
    "(UTC - 4.0) America/Montserrat",
    "(UTC - 4.0) America/Aruba",
    "(UTC + 5.5) Asia/Colombo",
    "(UTC - 4.0) America/Guadeloupe",
    "(UTC + 8.0) Asia/Hong_Kong",
    "(UTC + 3.0) Indian/Mayotte",
    "(UTC + 1.0) Africa/Porto-Novo",
    "(UTC - 11.0) Pacific/Pago_Pago",
    "(UTC + 9.0) Asia/Pyongyang",
    "(UTC + 1.0) Europe/Busingen",
    "(UTC + 9.0) Asia/Khandyga",
    "(UTC + 1.0) Europe/Prague",
    "(UTC + 1.0) Europe/Monaco",
    "(UTC + 1.0) Europe/Paris",
    "(UTC - 4.0) America/Porto_Velho",
    "(UTC + 1.0) Arctic/Longyearbyen",
    "(UTC - 9.0) Etc/GMT+9",
    "(UTC + 13.75) Pacific/Chatham",
    "(UTC + 3.0) Asia/Istanbul",
    "(UTC + 2.0) Europe/Kaliningrad",
    "(UTC - 3.0) America/Argentina/La_Rioja",
    "(UTC + 2.0) Europe/Nicosia",
    "(UTC + 5.5) Asia/Kolkata",
    "(UTC + 1.0) Europe/Sarajevo",
    "(UTC + 10.0) Australia/Brisbane",
    "(UTC - 3.0) America/Argentina/Tucuman",
    "(UTC + 8.0) Asia/Brunei",
    "(UTC + 4.0) Indian/Reunion",
    "(UTC + 1.0) Africa/Ceuta",
    "(UTC - 8.0) America/Tijuana",
    "(UTC + 3.5) Asia/Tehran",
    "(UTC - 6.0) America/Belize",
    "(UTC - 4.0) America/Guyana",
    "(UTC + 7.0) Etc/GMT-7",
    "(UTC + 3.0) Asia/Aden",
    "(UTC - 4.0) America/Moncton",
    "(UTC - 5.0) America/Pangnirtung",
    "(UTC + 3.0) Africa/Addis_Ababa",
    "(UTC - 6.0) Etc/GMT+6",
    "(UTC + 3.0) Africa/Asmara",
    "(UTC - 3.0) Atlantic/Stanley",
    "(UTC - 6.0) America/Matamoros",
    "(UTC - 3.0) America/Argentina/San_Juan",
    "(UTC + 8.0) Asia/Manila",
    "(UTC - 6.0) America/Tegucigalpa",
    "(UTC - 4.0) America/Port_of_Spain",
    "(UTC - 9.0) Pacific/Gambier",
    "(UTC + 2.0) Europe/Riga",
    "(UTC - 10.0) Pacific/Honolulu",
    "(UTC + 8.0) Asia/Makassar",
    "(UTC + 7.0) Asia/Bangkok",
    "(UTC + 8.0) Asia/Ulaanbaatar",
    "(UTC - 5.0) America/Rio_Branco",
    "(UTC - 0.0) Etc/GMT",
]

TIMEZONE_TRIE = Trie([*ALL_TIMEZONES, *ALL_TIMEZONES_WITH_OFFSET])


@functools.lru_cache(maxsize=100)
def get_timezones_by_prefix(prefix: str = "", max_results: int = 8) -> List:
    if not prefix:
        return ALL_TIMEZONES
    return TIMEZONE_TRIE.keys(prefix=prefix)[:max_results]
